name: Landmarks
main: de.wecallit42.minecraft.landmarks.LandmarksPlugin
version: 0.1

commands:
  landmark:
    description: Set and remove landmarks.
    usage: |
           /<command> add [name]
           /<command> set [name]
           /<command> del [name]
